apiVersion: v1
kind: Service
metadata:
  labels:
    io.service: web
  name: web
spec:
  ports:
    - name: "8000"
      port: 8000
      targetPort: 80
  type: LoadBalancer
  selector:
    io.service: web
