apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.service: web
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      io.service: web
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.network/containerised-app-default: "true"
        io.service: web
    spec:
      containers:
        - image: web
          name: php
          ports:
            - containerPort: 80
              hostPort: 8000
              protocol: TCP
          volumeMounts:
            - mountPath: /var/www/html
              name: web-claim0
      restartPolicy: Always
      volumes:
        - name: web-claim0
          persistentVolumeClaim:
            claimName: web-claim0
